[build]
  publish = "."

[[redirects]]
  from = "/blog"
  to = "/blogs"
  status = 301

[[redirects]]
  from = "/blog/"
  to = "/blogs/"
  status = 301

[[redirects]]
  from = "/blog/*"
  to = "/blogs/:splat"
  status = 301
